### ISSUE TITLE
"cannot get length" when opening remote files in electron app

### ISSUE THREAD

**Issue by rbuels** [GMOD/jbrowse#1234]
![image](https://user-images.githubusercontent.com/73749/46983537-d6f6c080-d095-11e8-8c18-62967fc2f43e.png)

**Comment by cmdcolin** [comment]
I think old RemoteBinaryFetch would try and stat file only if it was electron environment and content-range wasn't accessible, annoying quirk:)

**Comment by rbuels** [comment]
Yeah, we replicated that in the new code. This bug seems to be coming from
a URL that does not support CORS, but I think I might have found a way to
get electron to ignore cors.

**Comment by cmdcolin** [comment]
@rbuels I think you're right about the headers being hidden basically being a CORS limitation. Did you have any update on how to workaround?

**Comment by cmdcolin** [comment]
One possible idea, swap out fetch for https://www.npmjs.com/package/electron-fetch where relevant...

**Comment by cmdcolin** [comment]
The electron.net module does not appear to exist in the window e.g. var electron = electronRequire('electron').net is undefined

However, the http/https modules do exist so this might be the way to go...

**Comment by cmdcolin** [comment]
At the very least, I hacked it a bit until it was able to load a simple remote file using the http/https module so that seems good :)

**Comment by cmdcolin** [comment]
#1245 PR attempts to address

**Comment by rbuels** [comment]
@cmdcolin i merged #1245, but what do you think about just disabling web security in electron?  that should smooth over the CORS thing too https://stackoverflow.com/questions/35852684/electron-chromium-disable-web-security

**Comment by rbuels** [comment]
or is that not necessary anymore with #1245

**Comment by cmdcolin** [comment]
@rbuels I tried doing that webSecurity false flag (with the camel cased not dash variables) but it didn't appear to fix it. I created #1245 in order to fix :)

**Comment by cmdcolin** [comment]
Testing on this is welcome I didn't add a unit test for it unfortunately just because I was hesitant to reference any specific URL for a test file and didn't want to spin up a local server or rely on the travis-ci test environment to make it pass :)

Otherwise, I suppose close for now!
